### ISSUE TITLE
undefined vnode.state

### ISSUE THREAD

**Issue by magnusleo** [StephanHoyer/mithril-query#50]
## Description:
`vnode.state` is not copied from `vnode.tag` when Mithril 1.0.0 "rewrite" is running in node.

### Steps to Reproduce:

Using this gist: https://gist.github.com/magnusleo/ac28737dd659db6465d9db47ab54495b
```
npm test
```

My test was run with node v5.9.1 on Mac OS X 10.11.5, installed using http://brew.sh/

### Expected:

The test runs flawlessly.

### Actual:

```javascript
component.js:15
                return m('li', {onclick: vnode.state.clickCurry(i)}, item); // Fails in node
                                                    ^

TypeError: Cannot read property 'clickCurry' of undefined
```

**Comment by StephanHoyer** [comment]
I just looked into it.

Simple solution was to also copy all of `tag` to `state`. Just did that.

But I think I should try again to use mithrils rendering directly (like @isiahmeadows recommended) in order keep up with changes there.

**Comment by magnusleo** [comment]
Thank you very much.

Without deeper knowledge, I agree that using as much of Mithril's rendering as possible is a good idea for the same reason you mentioned.
