### ISSUE TITLE
VNode children property of type boolean not handled

### ISSUE THREAD

**Issue by SL014066** [StephanHoyer/mithril-query#73]
When searching through VNode children, a boolean value can cause unexpected results.  

If the boolean is true (Ex. node.children === true), the short-circuit logic will interpret the children property as being truthy and continue past this check and then attempts to perform array function calls.
(line 179)
` if (!node.children || isStringOrNumber(node.children)) {
        return foundNodes
      }`

Adding a new isBoolean function and modifying the short-circuit logic should prevent this and return the expected results.

`function isBoolean (thing) {
    return typeof thing === "boolean";
}
...
if (isBoolean(node.children) || isStringOrNumber(node.children)|| !node.children) {
     return foundNodes
}`

**Comment by SL014066** [comment]
I've made updates for this in a fork if you would like me to submit a pull request

**Comment by StephanHoyer** [comment]
yeah, would be great. Also with proper test if possible

**Comment by StephanHoyer** [comment]
thanks for the fixes
