### ISSUE TITLE
'first' throwing errors when no vdom nodes identified.

### ISSUE THREAD

**Issue by SL014066** [StephanHoyer/mithril-query#74]
'first' is throwing errors when no results are found.  This results in other functions not returning the expected result.  For instance when using the 'contains' function, if the value is not contained in the vdom then an error is thrown rather than 'false' being returned.

out.contains(string) – Returns true if any element in tree contains the string, otherwise false.

Updating the contains function to utilize 'find' rather than 'first resolves this issue.

`  function contains (value, node) {
    return !!(find(':contains(' + value + ')', node).length);
  }`

**Comment by StephanHoyer** [comment]
Test and PR would be great here too!

**Comment by StephanHoyer** [comment]
thanks for the fix.
