### ISSUE TITLE
Cannot assign to read only property 'parent' of <tag>

### ISSUE THREAD

**Issue by magnetised** [StephanHoyer/mithril-query#9]
Running on node v0.12.4 `npm test` gives:

    17 passing
    15 failing

tests. All the failing tests fail with the same error call stack:

    TypeError: Cannot assign to read only property 'parent' of Test
      at index.js:108:22
      at Array.forEach (native)
      at matches (index.js:107:36)
      at find (index.js:82:44)

**Comment by StephanHoyer** [comment]
works in node 4.1
